project_id = "zfefnlibzgkfbgdtagho"

[functions.encrypt-api-credentials]
verify_jwt = true

[functions.test-broker-connection]
verify_jwt = true

[functions.sync-real-balance]
verify_jwt = true

[functions.analyze-multi-timeframe]
verify_jwt = false

[functions.execute-order]
verify_jwt = true

[functions.monitor-positions]
verify_jwt = false

[functions.close-position]
verify_jwt = false

[functions.sync-binance-positions]
verify_jwt = true

[functions.ia-daily-training]
verify_jwt = false

[functions.ia-historical-training]
verify_jwt = false
